version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Rome"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"
    groups:
      go-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Rome"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10
